### ISSUE TITLE
Could not parse contracts

### ISSUE THREAD

**Issue by okwme** [nomiclabs/truffle-flattener#28]
```
Error: Could not parse contracts/Clovers.sol for extracting its imports.
    at getDependencies (/usr/local/lib/node_modules/truffle-flattener/index.js:50:11)
    at dependenciesDfs (/usr/local/lib/node_modules/truffle-flattener/index.js:69:24)
    at <anonymous> 'Error: Could not parse contracts/Clovers.sol for extracting its imports.\n    at getDependencies (/usr/local/lib/node_modules/truffle-flattener/index.js:50:11)\n    at dependenciesDfs (/usr/local/lib/node_modules/truffle-flattener/index.js:69:24)\n    at <anonymous>'

```

while trying w contracts located at https://github.com/clovers-network/clovers-contracts

works w `contracts/ClubToken.sol` and `contracts/ClubTokenController.sol` but not with `contracts/Clovers.sol` or `contracts/CloversController.sol`

**Comment by alcuadrado** [comment]
Closing because #30 fixed this. Thanks!
