### ISSUE TITLE
Having a variable named "calldata" makes things explode.

### ISSUE THREAD

**Issue by pierce403** [nomiclabs/truffle-flattener#32]
Here's a simple contract that uses a variable named "calldata" that is unabled to be flattened.  Renaming "calldata" to "potatodata" makes everything work as expected.

```
pierce403@penguin:~/fun/potato/contracts$ cat Potato.sol 
pragma solidity ^0.4.24;

contract Potato {
  function yay() public pure {
    string calldata="hello";
  }
}
pierce403@penguin:~/fun/potato/contracts$ truffle-flattener Potato.sol 
Error: Could not parse contracts/Potato.sol for extracting its imports.
    at getDependencies (/home/pierce403/node/lib/node_modules/truffle-flattener/index.js:56:11)
    at dependenciesDfs (/home/pierce403/node/lib/node_modules/truffle-flattener/index.js:75:24)
    at <anonymous> 'Error: Could not parse contracts/Potato.sol for extracting its imports.\n    at getDependencies (/home/pierce403/node/lib/node_modules/truffle-flattener/index.js:56:11)\n    at dependenciesDfs (/home/pierce403/node/lib/node_modules/truffle-flattener/index.js:75:24)\n    at <anonymous>'
pierce403@penguin:~/fun/potato/contracts$ sed -i 's/calldata/potatodata/g' Potato.sol 
pierce403@penguin:~/fun/potato/contracts$ cat Potato.sol 
pragma solidity ^0.4.24;

contract Potato {
  function yay() public pure {
    string potatodata="hello";
  }
}
pierce403@penguin:~/fun/potato/contracts$ truffle-flattener Potato.sol 
pragma solidity ^0.4.24;

// File: contracts/Potato.sol

contract Potato {
  function yay() public pure {
    string potatodata="hello";
  }
}
pierce403@penguin:~/fun/potato/contracts$ 
```

**Comment by alcuadrado** [comment]
Hi @pierce403, this is a bug in https://github.com/federicobond/solidity-parser-antlr, do you mind reporting it there? Thanks

**Comment by pierce403** [comment]
I'm not super confident about the actual nature of the bug, and am unsure how to extract it from the truffle-flatterer context.  If you are more familiar with that other project you would probabally be able to file the bug more convincingly.
