### ISSUE TITLE
Could not parse contract for extracting its imports.

### ISSUE THREAD

**Issue by vittominacori** [nomiclabs/truffle-flattener#51]
Hello have you any idea about why it is throwing this error when I moved to solidity 0.6?

```
Error: Could not parse @openzeppelin/contracts/token/ERC20/ERC20Detailed.sol for extracting its imports.
    at getDependencies (/path/erc20-generator-smartcontracts/node_modules/truffle-flattener/index.js:58:11)
    at dependenciesDfs (/path/erc20-generator-smartcontracts/node_modules/truffle-flattener/index.js:78:24)
```

It works on `master` branch but not [here](https://github.com/vittominacori/erc20-generator/tree/feature/solidity06).

**Comment by alcuadrado** [comment]
I just released a new version that should fix this. Please open a new issue if this problem is still present.
