### ISSUE TITLE
Error: None of the sub-resolvers resolved "@openzeppelin/contracts-upgradeable/token/ERC20/ERC20Upgradeable.sol" location.

### ISSUE THREAD

**Issue by Ju8z** [nomiclabs/truffle-flattener#94]
Hi, I know it was fixed here but smoehow im still having this problem. Contract version ^0.8.04

```
$ truffle run flatten ./contracts/MyToken.sol
artifactSource: ./contracts/MyToken.sol
Error: None of the sub-resolvers resolved "@openzeppelin/contracts-upgradeable/token/ERC20/ERC20Upgradeable.sol" location.
    at ResolverEngine.<anonymous> (C:\Users\asd\AppData\Roaming\npm\node_modules\truffle-flatten\node_modules\@resolver-engine\core\src\resolverengine.ts:34:13)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\asd\AppData\Roaming\npm\node_modules\truffle-flatten\node_modules\@resolver-engine\core\build\src\resolverengine.js:4:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Truffle v5.5.14 (core: 5.5.14)
Node v16.14.2
```

Truffle config
```
const HDWalletProvider = require('@truffle/hdwallet-provider');
const fs = require('fs');
const mnemonic = fs.readFileSync(".secret").toString().trim();

module.exports = {
    networks: {
        dev: {
            host: "127.0.0.1",     // Localhost (default: none)
            port: 8545,            // Standard BSC port (default: none)
            network_id: "*",       // Any network (default: none)
        },
        testnet: {
            provider: () => new HDWalletProvider(mnemonic, `https://data-seed-prebsc-1-s1.binance.org:8545`),
            network_id: 97,
            confirmations: 10,
            timeoutBlocks: 2000,
            skipDryRun: true
        },
        bsc: {
            provider: () => new HDWalletProvider(mnemonic, `https://bsc-dataseed1.binance.org`),
            network_id: 56,
            confirmations: 10,
            timeoutBlocks: 200,
            skipDryRun: true
        },
    },

    api_keys: {
   
        bscscan: 'blabla'
 
    },

    // Set default mocha options here, use special reporters etc.
    mocha: {
       // timeout: 100000
    },

    plugins: [
        'truffle-flatten',
        'truffle-plugin-verify'
    ],

    // Configure your compilers
    compilers: {
        solc: {
            version: "^0.8.14"  
        }
    }
}
```

any ideas why it occurs again, because ive zero problems with hardhat.. 
ty

**Comment by alcuadrado** [comment]
Does your project compile succesfully?
